---
# Resolve o host de controle com fallback robusto (evita delegate_to vazio)
- name: Resolve control-plane host for Helm operations
  ansible.builtin.set_fact:
    longhorn_cp_host: >-
      {{ (longhorn_control_host | default('')) |
         default( (groups[longhorn_master_group] | default([])) | first, true ) |
         default( (groups['controlplane']       | default([])) | first, true ) |
         default( (groups['master']             | default([])) | first, true ) |
         default( (ansible_play_hosts_all       | default([])) | first, true ) }}

# 0) Pré-requisitos (Longhorn data plane em todos os nós)
- import_tasks: node_prereqs.yml

# 1) Garantir helm no host de controle
- import_tasks: prereqs_helm.yml

# 2) Helm repo do Longhorn
- name: Add Longhorn Helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  run_once: true
  delegate_to: "{{ longhorn_cp_host }}"

- name: Helm repo update
  ansible.builtin.command: helm repo update
  changed_when: false
  run_once: true
  delegate_to: "{{ longhorn_cp_host }}"

# 3) Namespace + values
- name: Ensure namespace exists
  ansible.builtin.command: >
    kubectl --kubeconfig={{ longhorn_kubeconfig }}
    get ns {{ longhorn_namespace }}
  register: _ns_check
  changed_when: false
  failed_when: false
  run_once: true
  delegate_to: "{{ longhorn_cp_host }}"

- name: Create namespace if missing
  ansible.builtin.command: >
    kubectl --kubeconfig={{ longhorn_kubeconfig }}
    create ns {{ longhorn_namespace }}
  when: _ns_check.rc != 0
  run_once: true
  delegate_to: "{{ longhorn_cp_host }}"

- name: Template Longhorn values
  ansible.builtin.template:
    src: longhorn-values.yaml.j2
    dest: /tmp/longhorn-values.yaml
    mode: "0644"
  run_once: true
  delegate_to: "{{ longhorn_cp_host }}"

# 4) Instalar/atualizar o chart
- name: Install/Upgrade Longhorn via Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ (longhorn_chart_version | trim) if (longhorn_chart_version | trim | length > 0) else omit }}"
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    values_files:
      - /tmp/longhorn-values.yaml
    kubeconfig: "{{ longhorn_kubeconfig }}"
  run_once: true
  delegate_to: "{{ longhorn_cp_host }}"

# 5) Espera básica da UI
- name: Wait for Longhorn UI rollout
  ansible.builtin.command: >
    kubectl --kubeconfig={{ longhorn_kubeconfig }}
    -n {{ longhorn_namespace }} rollout status deploy/longhorn-ui --timeout=180s
  register: _rollout
  changed_when: false
  failed_when: false
  run_once: true
  delegate_to: "{{ longhorn_cp_host }}"
