controller:
  ingressClassResource:
    name: nginx
    controllerValue: "k8s.io/ingress-nginx"
    default: true
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.100.100
  extraArgs:
    enable-ssl-passthrough: "true"
  config:
    use-forwarded-headers: "true"
    proxy-body-size: "64m"
    proxy-read-timeout: "120"
    proxy-send-timeout: "120"
