---
- name: Build hosts entries (this node + master + extras)
  ansible.builtin.set_fact:
    _os_hosts_rows: >-
      {{
        (
          [
            {'ip': '127.0.0.1', 'name': 'localhost'},
            {'ip': (node_ip | default('')), 'name': (inventory_hostname | default(''))}
          ]
          +
          ([{'ip': master_ip, 'name': 'master'}] if (master_ip is defined) else [])
          +
          (os_hosts_extra | default([]))
        )
        | selectattr('ip','string')
        | selectattr('ip','ne','')
        | list
      }}

- name: Manage /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  when: os_manage_hosts
  become: true
