---
- name: Include packages
  ansible.builtin.import_tasks: packages.yml

- name: Include kernel settings
  ansible.builtin.import_tasks: kernel.yml

- name: Include sysctl tuning
  ansible.builtin.import_tasks: sysctl.yml

- name: Disable swap
  ansible.builtin.import_tasks: swap.yml

- name: Manage /etc/hosts
  ansible.builtin.import_tasks: hosts.yml

- name: Firewall baselines
  ansible.builtin.import_tasks: firewall.yml


- name: Ensure open-iscsi package is installed
  ansible.builtin.package:
    name: open-iscsi
    state: present
  become: true

- name: Ensure iscsid service is enabled and running
  ansible.builtin.service:
    name: iscsid
    enabled: true
    state: started
  become: true
