---
- name: Ensure open-iscsi package is installed
  ansible.builtin.package:
    name: open-iscsi
    state: present
  become: true

- name: Ensure iscsid service is enabled and running
  ansible.builtin.service:
    name: iscsid
    enabled: true
    state: started
  become: true
