---
galaxy_info:
  author: techaux
  description: "Hardening básico de OS para Kubernetes (VirtualBox/Vagrant, Ubuntu 22.04)."
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions: [jammy]
dependencies: []
