---
- name: Compute root DN
  ansible.builtin.set_fact:
    root_dn: "OU={{ root_ou_name }},{{ domain_dn }}"

- name: Run OU/GEO structure
  when: enable_ou | bool
  ansible.builtin.include_tasks: ou.yml

- name: Run People/Groups/Hierarchy
  when: enable_people | bool
  ansible.builtin.include_tasks: people.yml
