---
# roles/worker/tasks/main.yml

# 1) Fixar o IP do nó no kubelet (NIC bridged)
- name: Ensure kubelet uses bridged IP
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    create: true
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS="--node-ip={{ node_ip }}"'
    mode: '0644'

- name: Reload systemd and restart kubelet
  become: true
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl restart kubelet
  changed_when: false

# 2) Se já está no cluster, não tente join de novo
- name: Check if node is already part of the cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

# 3) Pegar o comando de join diretamente do master, sem depender de arquivos
- name: Pick master host (fallback para 'master' se grupo não existir)
  ansible.builtin.set_fact:
    _master_host: "{{ (groups['master'] | default([])) | first | default('master') }}"

- block:
    - name: Get fresh join command from master
      become: true
      ansible.builtin.shell: kubeadm token create --print-join-command
      delegate_to: "{{ _master_host }}"
      register: join_now

    # NÃO adicionar --node-ip aqui; kubelet já está configurado acima
    - name: Join the cluster
      become: true
      ansible.builtin.shell: "{{ join_now.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Enable kubelet service
      become: true
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
  when: not kubelet_conf.stat.exists
