---
- name: master
  hosts: all
  become: true
  tags: master

  roles:
    - os
    - containerd
    - kubernetes
    - master
    #- longhorn
    #- metallb
    #- nginx
    #- prometheus
    #- semaphore