---
# Onde rodar Helm/kubectl
prom_master_group: "master"              # ajuste se seu grupo for outro
prom_control_host: ""                    # opcional: forçar (ex.: "master")
prom_kubeconfig: "/etc/kubernetes/admin.conf"

# Chart / release
prom_namespace: "monitoring"
prom_release_name: "kube-prometheus"
prom_chart_version: ""                   # vazio = última estável
prom_repo_name: "prometheus-community"
prom_repo_url: "https://prometheus-community.github.io/helm-charts"
