---
galaxy_info:
  role_name: metallb
  author: "Kleyton Santos | Orcrist"
  description: "Ansible role to install and configure MetalLB for Kubernetes on Ubuntu."
  company: "Technologicum Auxilium (techaux)"
  license: "MIT"
  license_file: "LICENSE"
  min_ansible_version: "2.12"

  maintainers:
    - name: "Kleyton Santos"
      email: "kleyton@techaux.com.br"
      github: "kleytonhsantos"

  project_url: "https://github.com/technologicum-auxilium/ansible-role-metallb"
  issue_tracker_url: "https://github.com/technologicum-auxilium/ansible-role-metallb/issues"
  documentation_url: "https://techaux.com.br/docs/ansible-role-metallb"
  homepage: "https://techaux.com.br"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

  galaxy_tags:
    - metallb
    - load-balancer
    - networking
    - kubernetes

dependencies: []
collections:
  - kubernetes.core
